packages:
  # include packages in subfolders (change as required)
  - 'packages/**'
  - 'examples/**'
  - 'website'
  - 'snippet'
    # exclude the git submodule (and everything inside it)
  - '!packages/pdfium/pdfium-src/**'